### ISSUE TITLE
[valarray] wording needs major overhaul

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#1071]
This is a large piece of work.
The valarray section does not use the standard section labels,
Requires/Effects/Returns/etc. using free-form text to try to
establish the same guarantees.  Other than looking like bad
style, this form of presentation has grown to grant explicit
meaning through these terms, and the valarray specification
would be much clearer if adapted.

**Comment by jensmaurer** [comment]
I can't believe this to be editorial. Rephrasing large bodies of text always risks a subtle semantic change, so this should really be an LWG issue.

**Comment by jensmaurer** [comment]
See also #232.

**Comment by AlisdairM** [comment]
I think editorially, we can incrementally improve these clauses in various ways without triggering a large paper and asking library to review it - as I believe LWG would rather focus its limited resources elsewhere.  Editorially, I think this subclause is far from satisfactory in its current shape, given the improving structure of library clauses over time.  Continuous refinement to avoid normative changes though, definitely makes this a 'big' task.

**Comment by sigfpe** [comment]
Whatever we do, I recommend extreme caution. Be careful about edtorial fever overreach.
-------- Original message --------From: Alisdair Meredith <notifications@github.com> Date: 11/20/16  11:19 AM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: Re: [cplusplus/draft] [valarray] wording needs major overhaul (#1071) 
I think editorially, we can incrementally improve these clauses in various ways without triggering a large paper and asking library to review it - as I believe LWG would rather focus its limited resources elsewhere.  Editorially, I think this subclause is far from satisfactory in its current shape, given the improving structure of library clauses over time.  Continuous refinement to avoid normative changes though, definitely makes this a 'big' task.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cplusplus/draft","title":"cplusplus/draft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cplusplus/draft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AlisdairM in #1071: I think editorially, we can incrementally improve these clauses in various ways without triggering a large paper and asking library to review it - as I believe LWG would rather focus its limited resources elsewhere.  Editorially, I think this subclause is far from satisfactory in its current shape, given the improving structure of library clauses over time.  Continuous refinement to avoid normative changes though, definitely makes this a 'big' task."}],"action":{"name":"View Issue","url":"https://github.com/cplusplus/draft/issues/1071#issuecomment-261798643"}}}

**Comment by AlisdairM** [comment]
yup - agree that appropriate caution is needed too.

**Comment by jensmaurer** [comment]
@AlisdairM: After #1215 went in, could you please re-check and name a few examples where we still need improvement, in your opinion?

**Comment by AlisdairM** [comment]
#1215 covers the major concern I had when opening this ticket, and would be happy to close it as resolved, picking up anything else we later find as separate issues.
