### ISSUE TITLE
[mem.res] Miscellaneous changes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1259]
[mem.poly.allocator.mem] p1
"Returns: Equivalent to" should be "Effects: Equivalent to"

[memory.resource.pool.options] p3
"pass-through threshold" is undefined, and the phrasing seems to allow arbitrary implementation behavior (I've asked for an LWG issue.)

<del>[alg.random.sample] p1.3
remove "additional" (twice)</del> [objected to by @W-E-Brown  --jensmaurer]

**Comment by W-E-Brown** [comment]
[alg.random.sample] p1.3
remove "additional" (twice)

I see no typo as claimed, nor any reason to remove "additional" even once here. Things are written the way they are for a reason.

<diatribe>
I fear we've been going waaaaaaay overboard in our enthusiasm for making largely-unnecessary changes. Let's keep in mind that every change has to be audited and approved by the WG21 membership. Instead of the few dozen that our colleagues could reasonably expect based on the latest approved motions, we've already provided many hundreds of deltas. (Just look at the length of the latest Editor's Report.)  Every single change potentially adds to the CWG/LWG workload. Don't they already have enough to do?

Every gratuitous change risks a loss of consensus, especially at this very late (post-ballot) stage. Enough is enough, guys and gals; there's such a thing as "abuse of discretion", after all, and IMO we're well past that. Making a change just because we don't like something simply isn't a good enough reason to do so. (In fact, it's a _terrible_ reason, IMO.)

I'm strongly considering recommending against adopting N4618, just based on the sheer volume of what seem to me to be mostly unplanned and unnecessary post-ballot editorial changes.  (And we've had how many hundred more since then?)
</diatribe>

**Comment by jensmaurer** [comment]
@W-E-Brown: Thanks for your remarks. I've changed the title of the issue.
I'm feeling that a github issue is probably not the right place for such rather general discussions; maybe the -edit reflector is more appropriate?

I'd like to point out that we always had a bunch of editorial changes (some larger, some smaller) in addition to the voted-on motions going into any meeting. Part of the trust WG21 endows in the Project Editor is "no normative surprises" for those editorial changes. If you have specific examples where the Project Editor or any of us have, in your opinion, crossed the line, please say so. Note that the presence of an editorial issue doesn't mean we'll implement what's described there, and raising objections in the editorial issue or the pull request is fine at any time.

In general, the papers we vote into the standard are written by individual authors, not all of them privy to the details of the formatting and presentation style we use for the standard. And not all deviations get caught during LWG review. So, post-CD is as good a time as any to turn the patchwork of papers into a coherent presentation.

"Every single change potentially adds to the CWG/LWG workload." CWG/LWG do not review editorial changes, as far as I know. In contrast, I believe a tad more aggressive editorial fixes ease the workload of CWG/LWG by preventing issues to come to them in the first place.

**Comment by zygoloid** [comment]
@W-E-Brown If you believe we've overstepped reasonable editorial discretion with any particular change, please let me know and I'll make sure that change is reverted for the next working draft. I'm generally always happy to push an editorial change through CWG/LWG instead of applying it editorially if any committee member requests it be handled that way (but doing so obviously increases the workload of CWG/LWG and their chairs and adds time in plenary).

**Comment by Eelis** [comment]
I agree with jensmaurer and zygoloid; the complaint would be significantly easier to substantiate if concrete examples of alleged inappropriate changes were provided.

**Comment by jensmaurer** [comment]
[mem.poly.allocator.mem] p1 is addressed by #1815.

**Comment by jensmaurer** [comment]
[memory.resource.pool.options] p3 is covered by [https://cplusplus.github.io/LWG/issue2848](LWG 2848).
