### ISSUE TITLE
[sf.cmath] association of Greek math variables with parameters fails

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1291]
We say, for example, `where $nu$ is \tcode{nu} and $x$ is \tcode{x}`, but we should say `where $\nu$ is \tcode{nu} and $x$ is \tcode{x}` so that we associate the Greek symbol used in the formula with the parameter, not some italics "nu" that appears nowhere else.

This affects the entire section.

**Comment by W-E-Brown** [comment]
I don't know the origin of those phrases; they don't exist in N3060 (the FDIS for IS 29124), so I didn't write them.  I agree that in their present form they're more confusing than helpful, so should be struck (my preference) or fixed.

(I'd rather see all these phrases gone because I find them redundant.  In each case, the wording already previously states that we're calculating a function of the respective named function parameters.  These phrases seem merely to repeat that information.  Further, the purpose of the formulas is not to prescribe any algorithm, but to remove possible ambiguity regarding the functions' definition:  the mathematics literature in several cases has multiple conflicting definitions that depend on the authors being consulted.  Tying these pure definitions to the named parameters seems wrong.)

But yes, if we must keep them, then we must certainly correct these phrases.

**Comment by tkoeppe** [comment]
I agree. At first glance this would look like a simple editorial error to me by which the backslash was forgotten. If anyone could trace the origins of this to confirm that'd be great, but it definitely looks defective it its present form.

@W-E-Brown: I don't think the phrasing is entirely redundant, since the mathematical symbols are not *a priori* identified with any C++ identifiers, and I would much rather make such identifications explicitly than assume some kind of magic mapping. (We are sloppy with this in parts of [algorithms], too, but often that's just down to tentative typography and not actual wording like here.)

**Comment by timsong-cpp** [comment]
This was added in 9b18983.
