### ISSUE TITLE
"main()" vs. "main function"

### ISSUE THREAD

**Issue by alexanderkscott** [cplusplus/draft#1304]
Excerpts from the standard:

> are not caught by a *function-try-block* on `main()`.
> a program whose function `main()` contains
> Control can be transferred directly to such a `main()` by throwing an exception that is caught in `main()`.

In my opinion, the empty parentheses look sloppy and "`main` function" would be better.

Another question is whether the "main" should be in code font. Currently there are a few instances of both "main function" (normal font) and of "`main` function" (code font).

**Comment by jensmaurer** [comment]
Yes, the parens should go.

In my opinion, "main" function should be code font: It's a bit of text that appears verbatim in user source code, and we're actually talking about the function spelled that way. (As opposed to, say, an inline function, which may or may not be declared with the `inline` keyword.)

**Comment by tkoeppe** [comment]
We still have a fair amount of places where we confuse functions and function calls. I recommend deciding on a direction with @zygoloid before putting any work into this.

**Comment by jensmaurer** [comment]
@tkoeppe: I'm sorry, I don't see you point in the context of the "main" function. We might have confusion between a function and a function call somewhere (examples?), but this issue is clearly not about calls, but about the structure of the "main" function. ("main" can't be called by the user, anyway.)

I'll prepare a patch to use \tcode{main} everywhere, plus a cross-reference to [basic.start.main]. These improvements should also address any questions whether, in some cases, a member function "main" might be meant (it isn't).
