### ISSUE TITLE
Inconsistent use of \colcol vs. ::\brk{}

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1359]
`\colcol` is defined to allow line breaks before and after the colon. Yet, we also use `::\brk{}` fairly often.

`\colcol`  48
`::\brk{}` 31

For comparison, total lines with `::` 4086.

We should harmonize this somehow. Suggestions:

- (1) Replace `::\brk{}` with \colcol
- (2) Replace `\colcol` with `::\brk{}` where still necessary (otherwise plain `::`) and remove the macro.
- (3) Replace all `::` in running text with \colcol to give LaTeX more line break opportunities, possibly improving layout in a few cases.

My recommendation is (1) or (2). Opinions?

**Comment by tkoeppe** [comment]
Partial idea: whenever `\colcol` can be replaced by just `::` with no visual change, we should do that.

**Comment by tkoeppe** [comment]
Option 2 seems best to me. It's consistent with our use of non-breaking spaces before references (`foo~(\ref{bar})`): We know that we *could* break there in a crunch, but we don't want to by default, and breaks should be applied manually. By the same token, we should have `::` as the default, and we should insert `\brk{}` as a manual override if needed.

I am also loosely considering the idea of deleting all `\brk{}`s after publication and only reinserting them before the next publication. This isn't a serious suggestion, but I'd like to think of this as the mental process. We should probably try and tidy up hyphenation hints regularly, since they're the very model of brittle things that rot almost immediately.

**Comment by jensmaurer** [comment]
@tkoeppe: I'm not sure about hyphenation and line-break hints rotting instantly; most of the text in the standard seems to be quite stable.
