### ISSUE TITLE
[variant.assign], [variant.swap]: place \item before or after "Otherwise,"?

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1398]
In other places, the \item marks are placed before "Otherwise".
In [variant.assign] and [variant.swap] the lists are not, "Otherwise," are at the end of the previous list items.

**Comment by jensmaurer** [comment]
It seems to me we usually have the "Otherwise" at the start of a bullet, but @zygoloid should decide.

See #122 for a related issue.

**Comment by tkoeppe** [comment]
We also have `, otherwise` a the end of items elsewhere, and we also have items like `\item foo bar, otherwise.`

I wonder whether this is something that *needs* to be changed for "more consistency". It seems perfectly understandable as is. I don't quite  feel a strong need for prescribing precise wording structures for such a large and loose category of statements.

**Comment by lynnboy** [comment]
For human readers this is ok, but the sentence boundaries are interleave with bullet boundaries here. Other lists having `, and`, `, or`, and `, otherwise` at least don't splitting sentences.
IMO, we'd better at least change `. Otherwise` to `; otherwise`.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: If you have a ". Otherwise...", the "Otherwise" goes at the start of the next bullet. Fix [variant.assign] and [variant.swap].
