### ISSUE TITLE
[class.dtor]/5

### ISSUE THREAD

**Issue by W-E-Brown** [cplusplus/draft#144]
[class.dtor]/5:  It seems that the sentence "A destructor is trivial if ..." ought to be the start of a new paragraph, as its topic has almost nothing in common with the preceding part of the current paragraph.  I recommend inserting \pnum before the quoted sentence.

In the same sentence, I recommend italicizing the first occurrence of "trivial" so as to clarify that this term is being defined, and so as to match the current typography of the paragraph's final sentence (which defines "non-trivial" and italicizes accordingly).

**Comment by jensmaurer** [comment]
I'm adding the paragraph number, but the differing typography of "trivial" vs. "non-trivial" is actually consistent with 12.8 [class.copy].

I'm not sure we should italicize "non-trivial" (or "trivial"), since it's not the unique definition of the technical term. Please open a new editorial issue if you feel strongly about that; this needs advice from the Project Editor.
