### ISSUE TITLE
LWG 2260 and 'r'

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1592]
The P/R of [LWG2260](https://wg21.link/lwg2260) (adopted in Kona '17) was written when the descriptive variable definitions (Table 27 in N4140) included a variable called [`r`](https://timsong-cpp.github.io/cppwp/n4140/allocator.requirements#tab:desc.var.def).

Then https://github.com/cplusplus/draft/commit/d2afc9a9b06e8fc495d94506620e54c0b62b36fc editorially removed that variable as unused, but the P/R of the issue was never updated. So now the allocator requirements table contains a dangling reference.

**Comment by jwakely** [comment]
Adding a row for `r` pushes the last row onto a new page, and then there's a `\newpage`, which creates an almost empty page. Removing the page break seems to be OK. @tkoeppe was that the one added because of the weird table spilling into the footer?

An alternative might be to use `*p` instead of `r`. That would be an expression of the correct type, but looks a bit strange to state the requirement on `pointer_to` in terms of a `X::pointer` object, because you wouldn't need to use `pointer_to` if you had `p` already.

**Comment by tkoeppe** [comment]
Feel free to put the `r` back in and remove the `\newpage`. The latter is situational.

**Comment by jwakely** [comment]
I'm leaning towards using `*p` instead of `r`, and adding an assertion that the result is equal to `p`.
