### ISSUE TITLE
"well formed" vs. "well-formed"

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#1618]
Those seem to be used more or less interchangeably in the standard.  Are they the same? If so, shouldn't they be written the same way?

"Well formed" --> 100+ uses
"Well-formed" --> 22 uses.

I can provide a list upon request.

**Comment by jensmaurer** [comment]
My understanding of the rules of English grammar is that we need a hyphen if we have a compound adjective, and we shouldn't have one if it's a verb + adverb "well" combination.

For example, "a well-formed program" is a program that has a certain property (adjective), but "the program is [well] formed" does not have a hyphen ("well" is adverb; replace with "quickly" if you wish).

That said, our use of "well-formed" seems to get a life of its own as a stand-alone adjective, so the verb interpretation along "is formed well" turns out to be rather odd. We should converge to "well-formed".

**Comment by jensmaurer** [comment]
I count only 20 or so occurrences of "well formed".

**Comment by burblebee** [comment]
I'm happy with well-formed.  Although I think we might want to finish applying the motions before merging any PRs.  Hopefully we'll be done soon...
