### ISSUE TITLE
[locale.moneypunct.virtuals] Footnote on moneypunct::do_curr_symbol could be more helpful

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1646]
It's very hard to find out what the `Intl` template parameter of `std::moneypunct` is supposed to mean.  [locale.moneypunct] says nothing about that template parameter. The only clue is a footnote in [locale.moneypunct.virtuals] which mentions

>  For international specializations (second template parameter `true`) this is typically four characters long, usually three letters and a space.

It would be helpful to refer to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) codes. Maybe also mentioning somewhere that "international specializations" may have a different currency symbol.

Maybe all the footnotes in the [locale.categories] subclause should be notes, not footnotes.

**Comment by jensmaurer** [comment]
How much of that is editorial? The utter lack of normative wording for the "International" template parameter can't be fixed editorially, it seems. We can certainly pimp the footnote to refer to ISO 4217, though.

The particular footnotes for `std::moneypunct` seem the right thing, because they give specific examples and hints for US locales instead of offering general remarks.
