### ISSUE TITLE
Placement of "*" and "&" inconsistent

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#166]
The prevailing style is "int& foo" and "int\* foo". I fixed pointers to be more consistent in ce29631dccd86d1e1eefff24d1dd3420c598258d; fix references too.

**Comment by tkoeppe** [comment]
Very unlikely do be done.

**Comment by timsong-cpp** [comment]
I did test several different regexes before submitting #1183 and didn't find anything else.

**Comment by tkoeppe** [comment]
Things that come to mind:

* angle brackets
* ellipses
* `decltype`
* casts (new- and old-style)

**Comment by timsong-cpp** [comment]
I just looked again at every case of `[[:space:]]&[^[:space:]]` and `[a-zA-Z)>._][[:space:]]&$` and every case of `\&` preceded by a space (for inline code).

The only one remaining is `Tid \cv{} \&` in the description of `bind`, but that one's odd because removing the space means attaching `&` to the placeholder *cv*.

**Comment by tkoeppe** [comment]
OK, thanks a lot for checking! Let's close this then.
