### ISSUE TITLE
Avoid "requirement" as a grammar non-terminal

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#1671]
P0734R0 contains _requirement_ as a grammar non-terminal.
The Working Draft prior to integrating P0734R0 already uses "requirement" with another meaning.

In this case, it would presumably be less disruptive to change P0734R0 to avoid "requirement" as the name of a grammar non-terminal. _req-stmt_ may be appropriate. Additionally, P0734R0 uses "requirement" to also refer to the semantics that the _requirement_ non-terminal applies. These uses may be modified to refer instead to the "enforced properties of the _req-stmt_".

**Comment by jensmaurer** [comment]
I agree with the general sentiment, but "enforced properties of the req-stmt" sounds contrived. Oh, and "req-stmt" is not really a statement, right?

**Comment by jensmaurer** [comment]
The worst conflict is probably [structure.requirements].

**Comment by hubert-reinterpretcast** [comment]
Yes, _req-stmt_ is not really a statement. It does act very similarly to a _static_assert-declaration_ though. So we could have _requirement-declaration_ and "declared requirements".

**Comment by zygoloid** [comment]
The grammar term *requirement* is used only in a very limited scope, and in the C++ wording (unlike C) we don't intend to have an implied correlation between grammar term *foo* and the English word "foo" used elsewhere in the text. As such, and because *requirement* is the most natural term for an element in a `requires` expression, I don't see sufficient motivation to make a change here.

**Comment by hubert-reinterpretcast** [comment]
The lack of the implied correlation is precisely what the second half of this issue points to. For example, see the unitalicized instances of "requirements" in 8.1.7 [expr.prim.req] paragraph 6.
