### ISSUE TITLE
[C++17 DIS comment 014] [alg.reverse] reverse has two Requires: clauses

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1726]
Figure out what happened here: how did we end up with two Requires: clauses that say the same thing in different ways? Then fix.

**Comment by cpplearner** [comment]
The first one was introduced in https://github.com/cplusplus/draft/commit/cf099ae6b4fccd8a98bf03c46cdd3110d9cd9d69, second one in https://github.com/cplusplus/draft/commit/5c0f40cae5424a1fe5cb4c720e2ce51e54c67dec.

**Comment by jwakely** [comment]
Thanks, it looks like the merge of cf099ae6b4fccd8a98bf03c46cdd3110d9cd9d69 to reorder the elements restored the old form of the _Requires:_ instead of moving the new form that had just been edited by 5c0f40cae5424a1fe5cb4c720e2ce51e54c67dec

So the fix is to removethe first one, and move the second one up to that place.

**Comment by jwakely** [comment]
Reopening, because this was only fixed on master. The commit will need to be cherry-picked and the conflict resolved for the c++17 branch.

**Comment by tkoeppe** [comment]
Commit in master: https://github.com/cplusplus/draft/commit/59da42bf51ac991ca7c63a3b3de6d53f8ce3d9a1

**Comment by zygoloid** [comment]
Looks good, resolution: ACCEPTED WITH MODIFICATIONS. Existing p1 deleted, p3 moved to p1.

**Comment by zygoloid** [comment]
Merged to c++17 as 89801f1a.
