### ISSUE TITLE
[C++17 DIS comment 017] Convert to UK English spelling

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1729]
Not clear that this is feasible, but we can at least check for common UK / US English differences

**Comment by tkoeppe** [comment]
If we currently have correct, pure-US spelling, then changing it piecemeal would seem to be a regression. Maybe we can explain that this is a considerable effort and we'll do it for C++20?

**Comment by jwakely** [comment]
The big one is "undefined behavior". I think "program" is OK in UK English, even if traditionally it would be programme.

There's an `enum color` in an example in [dcl.enum], which is OK for an example, although the text after it says "colors". The second half of the example could use `enum class Colour` instead of `enum class Col`. There's another `enum color` in [diff.dcl].

We can't change the `errc::operation_canceled` enumerator.

[category.messages] talks about "catalogs", but we can't change the `messages_base::catalog` type.

[re.traits] says "honor".

This is not an exhaustive list.

**Comment by jensmaurer** [comment]
I would expect all program-level things (e.g. class names in the standard library) to be spelled with US spelling, out of tradition. It seems odd to convert the rest of the text to UK spelling. In any case, that's some serious effort at the last minute to get right throughout. Do we have a channel to ISO to ask whether they will reject publication if we don't fix this for C++17? After all, all previous standards were published with US spelling.

**Comment by tkoeppe** [comment]
Note that among the dictionaries suggested by the drafting directives is the US English Websters. Perhaps we could arrive at a permanent settlement that we use US English, because many of the constructions in the language itself do, and it would be less confusing to use a single variant everywhere.

**Comment by zygoloid** [comment]
Response: REJECTED. The document defines many terms that must be spelled the same way by conforming implementations and by users of those implementations, and these terms use US English spelling. It would be confusing for the document text to use UK English spelling when describing these terms.
