### ISSUE TITLE
[C++17 DIS comment 019] Document has lists of tables and figures, xrefs, and indices

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1731]
Unclear what action is expected here. The "Proposed Change" does not propose a change. Suggestion: accepted, no change.

**Comment by tkoeppe** [comment]
I assume the perceived problem here is that different styles of naming are used for index-like constructions: "List of X" for tables and figures, just "Cross references" without any keyword, and "Index of X" for various indexes.

However, all this seems entirely sensible, because each heading says precisely what it means. We could contort ourselves and say "Index of cross references", but it would be baroque.

**Comment by zygoloid** [comment]
The proposed resolution says: "The ISO template does not support these elements but, as a PDF-only submission, SC22 is responsible for the accuracy of these elements."

I don't see how that's a proposed resolution at all, unless what they want us to say is "we resolve to take responsibility for the accuracy of these elements"...

**Comment by tkoeppe** [comment]
Hm, I believe the drafting directives also don't say that you should, or can (?) have a table of contents. Yet the checklist at the end says you should check the table of contents. Nor does it seem to mention indexes. It seems reasonable to me that the directives give leeway to include such tables, and it doesn't seem like a stretch that indexes should be allowed.

**Comment by jensmaurer** [comment]
If we don't change anything in response to the comment, I guess it's REJECTED with the rationale "The mentioned parts are vital in navigating our 1600-page document. They are machine-generated and therefore automatically remain synchronized with the document pagination and section numbering."

**Comment by zygoloid** [comment]
Jens' rationale sounds good to me.
