### ISSUE TITLE
[C++17 DIS comment 022] Change from letter to A4

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1734]
Suggestion: reject. We cannot do this at this point without risking large numbers of practically unreviewable reflow changes.

However, we should make this change in master to avoid this problem for C++20 onwards.

**Comment by tkoeppe** [comment]
Agreed on both counts, though I don't think we use "letter" at the moment, either; we use "ebook". I have always wondered about that.

**Comment by zygoloid** [comment]
I think that means our response is REJECTED. We need to draft an explanation. How about:

"This change will be made for future revisions of this standard. For the current standard, this change would result in extensive formatting changes, invalidating existing National Body comments."

**Comment by tkoeppe** [comment]
"... and potentially creating new objectionable formatting that NBs can no longer respond to."?

**Comment by jensmaurer** [comment]
@tkoeppe: "we use "ebook". I have always wondered about that"

We wanted a paper size that has the width of A4 and the length of US letter, allowing printing on both US and A4 formats without chopping off parts of the text. Let's NOT do this for C++17, but change it for C++20 right now.

**Comment by tkoeppe** [comment]
Well..... we *could* change the paper size but adjust the margins so that the column stays exactly the same, and we should get no change in the text flow. Printing could then also proceed as usual, just cropping differently. But we certainly don't have to do that.

This does however raise the more interesting question of whether a change of the individual dimensions is requested. If not, the request effectively amounts to adding whitespace at the top and bottom.

**Comment by tkoeppe** [comment]
Actually, memoir's `ebook` size is 6" x 9", not related to letter (8.5" x 11").

**Comment by zygoloid** [comment]
For consideration post-C++17.

**Comment by tkoeppe** [comment]
This has happened in 89842a31a4f054308c07e26a4bc13b688bd85743.
