### ISSUE TITLE
[complex.value.ops] and [complex.transcendentals] contain failed attempts to xref the C standard

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1822]
Example:

![screenshot from 2017-11-17 18 38 51](https://user-images.githubusercontent.com/232783/32976209-95f7664a-cbc6-11e7-8ae3-0bfaa25796c9.png)

Err, no, that's not how we write cross-references to C.

Also, due to the nonstandard formatting, these were missed when rebasing on C11. The first xref (to `cproj`) should refer to 7.3.9.5 not 7.3.9.4. (The rest, by sheer luck, still seem to be OK, but someone should double-check.)

**Comment by tkoeppe** [comment]
To the `\xref`s!

**Comment by jensmaurer** [comment]
@zygoloid: We usually put those `\xref` things in a (non-numbered) paragraph by themselves, and we use them only for functions actually inherited from C headers. In the present case, however, we describe C++ functions in `<complex>` by referring to the C definition of corresponding functions in <complex.h>.

For example,

> Remarks: Behaves the same as the C function cproj, defined in 7.3.9.4.

would be reworded as something like

> Remarks: Behaves the same as the C function cproj. See also ISO C 7.3.9.5.

Is that what we want?

On a related note, [structure.see.also] explicitly says we point to the C standard when using `\xref`, but that's a lie when looking at [depr.locale.stdcvt.req]. We should really have a `\refc{blah}` or so that does `\xref ISO C blah`.

**Comment by jensmaurer** [comment]
I've gone forward with the "See also" phrasing.

**Comment by jensmaurer** [comment]
Re-opened to reconsider \xref usage patterns and consistency.

**Comment by zygoloid** [comment]
Decision: we should change the description of "SEE ALSO:" in [structure.see.also] to cover cross-references to any normative reference, making the usage in [depr.locale.stdcvt.req] correct, and then check for other places we should be using this, such as [re.synopt] and [re.grammar] for ECMA-262 and various places in filesystem for POSIX probably.

Also add a `\xrefc` macro for the common "SEE ALSO: ISO C" cases.
