### ISSUE TITLE
[concept.common] LWG 3154: Confusing wording

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#2247]
[\[concept.common\]/(2.1)](http://eel.is/c++draft/concept.common#2.1):

> `C(t())` equals `C(t())` if and only if `t()` is an equality-preserving expression

What does "`C(t())` equals `C(t())`" mean? In particular, does it mean “the first two evaluations of `C(t())` yield equal result" or "all evaluations of `C(t())` always yield equal result"? If the latter, why doesn't the sentence read "`C(t())` is an equality-preserving expression if and only if `t()` is an equality-preserving expression"?

cc @CaseyCarter

**Comment by jensmaurer** [comment]
This phrasing has another issue, too: It says "if and only if", so if t() is not an equality-preserving expression, C(t()) must be different from C(t()). That seems impossibly to guarantee.
@CaseyCarter, you wanted to open LWG issues for the remaining open concepts items. Do you have one for this already?

**Comment by CaseyCarter** [comment]
This wording specifically (and the similar wording in [concept.commonreference]) came up during the final editorial review, and I'll be filing an LWG issue for it. I've been waiting for the updated WD to file my list of issues, since I suspect the LWG issue management utilities will fail horribly with issues that refer to stable names that don't exist in the working draft.

**Comment by timsong-cpp** [comment]
@CaseyCarter 
> since I suspect the LWG issue management utilities will fail horribly with issues that refer to stable names that don't exist in the working draft.

They'll be fine (it will just be ["Section 99"](http://cplusplus.github.io/LWG/lwg-index.html#Section%2099)). We have plenty of issues targeting stable names that no longer exist.

**Comment by jensmaurer** [comment]
LWG 3154 was adopted in San Diego.
