### ISSUE TITLE
Different vertical positioning of items in top-level clause summary tables

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2392]
![1541797347](https://user-images.githubusercontent.com/21071787/48288059-45366500-e441-11e8-9534-b8dd521dc0bf.png)
One subclase, various headers, first row positioning.

---
![1541797422](https://user-images.githubusercontent.com/21071787/48288115-6e56f580-e441-11e8-9c96-90c6149c7523.png)
Various subclauses, one header, first row positioning.

---
![1541797453](https://user-images.githubusercontent.com/21071787/48288142-80389880-e441-11e8-9ba2-cdb51d8c4857.png)
One subclase, various headers, centralized positioning.

---
![1541797587](https://user-images.githubusercontent.com/21071787/48288236-d4437d00-e441-11e8-94c3-c5f145dee19e.png)
Various subclauses, one header, centralized positioning.

---

I thought it might be desirable to decide on a style. I personally prefer the centralized positionings.

**Comment by johelegp** [comment]
> ![1541797422](https://user-images.githubusercontent.com/21071787/48288115-6e56f580-e441-11e8-9c96-90c6149c7523.png)

Should the (s) in Header(s) be dropped, or added to Subclause too?

**Comment by zygoloid** [comment]
* Yes, we should consistently apply one style.
 * If we use a vertically-centered style, we should do that properly (eg, `\multirow` rather than the current "put the text in the right cell, maybe off by half a row" approach)
 * Yes, we should consistently either pluralize or not pluralize the column headings
 * Also fix the summary table in [atomics.general] to remove the line separators between `<atomic>` entries

**Comment by jensmaurer** [comment]
@zygoloid, thanks for your input. However, there are a lot of "if"s here. Here are my preferences:
- use first row positioning
- do not pluralize the column headings (we also say "Subclause", not "Subclauses")
@tkoeppe, any opinion here?

**Comment by tkoeppe** [comment]
I agree with first-row positioning. Centering of any kind is "cute" but ultimately distracting. I also prefer staying on the baseline; on introspection I am finding this to be a rather strong preference.

I have no strong opinion on the plural issue, but I agree that the "header" and "subclause" columns deserve the same treatment, whatever that is. Plural may be a bit more accurate to how we end up using this column, but since many instances *don't* have more than one entry, a flat-out plural ("headers") might be confusing. But the parenthesized style ("header(s)") looks clunky, so I'm inclined to agree with Jens's suggestion to not pluralize.

Tangential: The overall visual style of the summary tables is abhorrent. I have a local patch to make my PDFs look less repelling; I'd welcome encouragement to propose changes.

**Comment by jensmaurer** [comment]
Editorial meeting:
- Vertically aligned at the top (first-row positioning).
- Singularize the headings; just say "Header" always.
- Fix "atomic" table.
- Left-align "Subclause" heading with the title.
- Linearize the headers (make it a list, comma-separated). Sort the header list lexicographically.
- Remove horizontal lines between sections having the same set of headers.
