### ISSUE TITLE
[2018-11 LWG Motion 12] P1148R0 Cleaning up Clause 20

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2418]
[P1148R0](http://wg21.link/p1148r0)

**Comment by burblebee** [comment]
@zygoloid I assume you'll be the official reviewer for this paper?  As with lwg-11, there's no PR so can't use that to assign the reviewer.  

Also, the sources just list the files - how do we see the changes in diff form from that (so we can review, comment, etc.)?  It seems there must be a way to do this in github (short of creating a PR from them).

**Comment by jensmaurer** [comment]
@burblebee: We can only directly use the sources if we have a common ancestor in the git version tree. Even then, we need to rebase to a reasonably recent commit and resolve the conflicts. Otherwise, the sources are just helpful input to create our own commit (because we don't have to redo all the formatting). Since @zygoloid is working on this, I suspect he'll do exactly this.

**Comment by timsong-cpp** [comment]
As implied by the intro to the paper, the base LaTeX for `strings.tex` and `iostreams.tex` in my repo was copied from the version used to generate N4762, which is pretty recent.

**Comment by johelegp** [comment]
> @burblebee: We can only directly use the sources if we have a common ancestor in the git version 

I don't think that's true. I believe all you need is the same directory structure. Then you can add that other repository as a remote and apply its commits to yours.

I have done this with two repositories of mine to easily adopt improvement to files somewhat generic to my projects, like `.travis.yml` and CMake modules. So far, I've only cherry-picked changes, though.

**Comment by zygoloid** [comment]
@johelegp That doesn't really work very well here. The paper sources have taken our sources and added `removed` and `added` markup for many of the changes, but some of the changes (eg, adding bullets and index entries) are not marked up at all. The paper sources make a great starting point, but there's still a large amount of manual effort required to apply these changes and be sure that we're only changing the things that we intended to change. (Eg, we can't just take the .tex and remove the "removed" parts, because that might result in unrelated / unintended changes to other parts of the draft -- in particular, loss of changes made in the interim.)

**Comment by burblebee** [comment]
Ignoring the apparent markup changes that @zygoloid spoke of in his comment above, I'd still like to know how to create a branch from a list of referenced source files, such as was supplied here.  Is it really as tedious as downloading all the files, creating a reverse diff from them back to the original paper they were based on,  and applying those diffs to the master sources?  There's got to be a way to use github to do this, no?

**Comment by jwakely** [comment]
@burblebee Given a Git repo, just set it as a remote and pull from it into a new branch.

Given a bunch of source files (not in a Git repo), create a new local branch, replace the files in your branch with the ones from the "list of referenced source files", commit. Now you have a branch containing those sources.
