### ISSUE TITLE
[algorithms] Long and unwieldly declarations

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2518]
With the addition of the ranges proposal, we now have even longer declarations in [algorithms], with multiple levels of indentation for template parameters and requires-clauses, plus return types mixed in between. This makes it hard to discern the vital parts, e.g. the _declarator-id_.

![decl](https://user-images.githubusercontent.com/23412755/49010919-fb55ba80-f174-11e8-8703-2c8b5378638b.png)

**Comment by jensmaurer** [comment]
Since the requires-clause is subordinate (in a way) to the template-head, maybe we can indent the requires-clause with two more spaces.

**Comment by CaseyCarter** [comment]
> Since the requires-clause is subordinate (in a way) to the template-head, maybe we can indent the requires-clause with two more spaces.

FWIW, that is the formatting that we used for template declarations with requires-clauses in the Ranges TS, primarily because it allows adding requires-clauses to a pre-existing declaration without reflowing the rest of the declaration. It's minimally intrusive, in that sense.

I think adding blank lines between the declarations of the range algorithm overloads would help readability more.

**Comment by jensmaurer** [comment]
Editorial meeting: Looks good as-is.
