### ISSUE TITLE
[iterator.concept.writable] Double if and one-item list

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2568]
https://github.com/cplusplus/draft/blob/38eb5e5e6209be9fce69e39ff721cd587791788e/source/iterators.tex#L1227-L1236

This one-item list starts with an if, but its introducing paragraph ends with an if too.

**Comment by jensmaurer** [comment]
And, reading through this, it seems intentional. The point here is that (beyond the syntactic requirements), a Writeable iterator that happens to also be a Readable iterator guarantees that you can read the just-written value back from the iterator. (Assuming the value types are the same.)
Just merging the duplicate "if"s would change the semantics.

**Comment by johelegp** [comment]
Right. After many rereads of your comment and the wording, I get it. Thank you.
