### ISSUE TITLE
decide what to do with underscores in section labels

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2609]
Continuing from #1498, we have 81 section labels containing underscores. These look extremely ugly: the font we use to display section labels does not have a reasonable underscore character.

We should either:

 * change the font used to render section labels (both in the body text and in xrefindex and xrefdelta) to have a less ugly underscore, or
 * revise the section labels to avoid using underscores

Generally when we form a section label from an identifier, we change underscores into periods (eg, [unord.map.syn] not [unordered_map.syn]); fixing these section labels to do the same may be the most consistent option.

**Comment by jensmaurer** [comment]
Let's revise the section labels, avoiding the underscores.
@tkoeppe consistently talks us out of having more font creativity in the standard.

**Comment by godbyk** [comment]
@tkoeppe Yes, we can redefine `\textunderscore` (which used behind the scenes when you type `_` in non-math mode) to draw our own underscore instead of using one from the font if we don't like the one from the font. By default, a 'fake' underscore is drawn if one isn't available in the font. It may be that the default fake one doesn't fit the design well and we should tweak it.

**Comment by timsong-cpp** [comment]
Speaking of ugly underscores, maybe we can do something about *static_assert-declaration* too.
