### ISSUE TITLE
CI meta-question

### ISSUE THREAD

**Issue by CaseyCarter** [cplusplus/draft#2642]
Question about the repository rather than its contents: who enabled Travis integration for `cplusplus/draft`? I put together some basic CI for `cplusplus/LWG` and checked it in a while back, but can't find someone with the permissions to enable Travis integration for the repo.

**Comment by godbyk** [comment]
@CaseyCarter I did the initial work on the `.travis.yml` configuration file. I think @zygoloid flipped the switch to grant Travis CI access to the repository, but I'm not sure on that. I think it requires a repository owner to enable the integration (but I'm not sure as Github has changed their user permissions model since I last dug into it).

**Comment by CaseyCarter** [comment]
No, I should have closed this years ago. Thanks!
