### ISSUE TITLE
[algorithms.general] Summary table missing row for [algorithms.requirements]

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2660]
All other Clauses with some form of "requirements" subclause list them in their summary, so it seems appropriate that [algorithms] does the same.

**Comment by johelegp** [comment]
Also consider adding [algorithms.parallel] to complement what's said in #2661.

**Comment by mesbrj** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Johel Ernesto Guerrero Peña <notifications@github.com> Date: 2/2/19  00:34  (GMT-03:00) To: cplusplus/draft <draft@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [cplusplus/draft] [algorithms.general] Summary table missing row for [algorithms.requirements] (#2660) 
All other Clauses with some form of "requirements" subclause list them in their summary, so it seems appropriate that [algorithms] does the same.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cplusplus/draft","title":"cplusplus/draft","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cplusplus/draft"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"[algorithms.general] Summary table missing row for [algorithms.requirements] (#2660)"}],"action":{"name":"View Issue","url":"https://github.com/cplusplus/draft/issues/2660"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cplusplus/draft/issues/2660",
"url": "https://github.com/cplusplus/draft/issues/2660",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
