### ISSUE TITLE
The term "full-expression" is not a grammar production

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2885]
Replace all references (38) to the term "full-expression" with "full expression", as a full expression is not a grammar production.

**Comment by cpplearner** [comment]
Is there a rule against using hyphen in a term? Plus, "full expression" suggest that it is a kind of expression, but it is not.

**Comment by jabelloc** [comment]
AFAICT this is the sole exception in the standard about what seems to be an informal rule.

**Comment by zygoloid** [comment]
We have other terms containing hyphens, such as cv-qualifier, parameter-type-list, injected-class-name, and so on. This is not a defect. Non-defining uses of such terms are formatted in upright text, which should visually distinguish them from grammar terms. There is, however, a visual ambiguity between the definition of such terms and grammar productions, but we discussed that in the context of #323 and decided to take no action.

**Comment by FrankHB** [comment]
I'm not trying to revive the issue (because it has nothing to do with hyphens vs. grammar production) but the current use of "full-expression" does have some problems raised from the hyphen. For instance, the localization (e.g. translation in the localized standards) of the ISO C++ rules is more difficult to be precise due to lack of hyphen in the result. This is not same to the cases like _cv_-qualifiers because prefixed _cv_ is not an adjective by itself, so the hyphen is preserved naturally.

Also @cpplearner, the fact that a full-expression is not necessarily a kind of expression makes the problem worse in another aspect. Why on earth such a context is named after a phrase of "expression"? (This does not seems to be editorial, though.)
