### ISSUE TITLE
[range.counted] Misplaced [range.counted]

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#2894]
`view::counted` is specified as a customization point object only. I think `view::counted` isn't designed to accept a range as its first argument, so it shouldn't be a range adaptor object.

However, [range.counted] is put in [range.adaptors] currently (N4810). How about move it to [range.factories]?

**Comment by johelegp** [comment]
See also https://github.com/ericniebler/stl2/issues/625.

**Comment by jensmaurer** [comment]
@CaseyCarter , you view on this?

**Comment by CaseyCarter** [comment]
It's not a range adaptor object, nor specified to be a range adaptor object. I do consider it nevertheless to be a range adaptor: it adapts the counted range `[i, n)` into the iterator+sentinel range `[i, i+n)` when `i` is random access or `[counted_iterator{i, n}, default_sentinel)` otherwise.

I think the source of the confusion here and in ericniebler/stl2#625 is that we've applied the too-generic term "range adaptor" - by association with the terms "range adaptor object" and "range adaptor closure object" - to a subset of the things that can reasonably be considered to adapt ranges. Ideally we'd devise a more specific name for that subset.
