### ISSUE TITLE
Counted ranges abuse mathematical notation

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2932]
Counted ranges are presented as

  [`A`, `N`)

but don't have the normal mathematical meaning; instead, they mean [`A`, `A`+`N`) (where the "+" means "the value that would be obtained by `N` applications of ++ to `A`" rather than `operator+`).

We should not abuse established mathematical notation in this way, and should find a different and unambiguous way to present counted ranges.

**Comment by CaseyCarter** [comment]
FWIW, +1 from me as the originator of this particular abuse of interval notation. It was originally less offensive since we used it in contexts where it was plain that the second member of the tuple is not a sentinel a la `[i, 42)`, but we've had to avoid using it in less clear contexts (`[i, n)` isn't horrible, but `[i, j)` surely is). This context-sensitivity is a clear indicator that overloading the syntax is a bad idea.

**Comment by tkoeppe** [comment]
I agree that we should not overload existing, established notation for counted ranges.

I don't have an "obvious" solution, but maybe we can define a slightly more elaborate device, maybe like `p + [0, N)` or so, to denote the set of iterators `p + 0`, `p + 1`,  ..., `p + (N - 1)`? Something like a pair of a starting iterator plus the set of all valid offsets?

**Comment by jensmaurer** [comment]
Editorial meeting: Define range of iterators. "Elements in the range" means dereferencing the iterators in the range. Use "`p` + [0,N)"
