### ISSUE TITLE
move [latch.syn], [thread.latch.class] under [thread.latch]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#3169]
The intended subclauses of [thread.latch] are at the same level as it rather than nested under it.

Note that fixing this will create a hanging paragraph under [thread.latch]. This should be fixed in some way. While fixing that, check the other subclauses of [thread] for hanging paragraphs; there are quite a few of them.

**Comment by dkolsen-pgi** [comment]
Regarding the hanging paragraphs:  In P1135 I was careful to word all the hanging paragraphs so that they are very general explanatory text.  They don't contain any definitions or normative requirements that might be referenced from anywhere else in the standard.  If I understand the hanging paragraph problem (which I'm not sure I do), this is the kind of text that could be left as a hanging paragraph.  (The italicized "latch" at the beginning of [thread.latch] should not be italicized.  It is not meant to be a definition that is referenced from anywhere else.  It is not italicized in P1135.)

If there is a strong desire to get rid of all hanging paragraphs, the text in [thread.sema], [thread.latch], and [thread.barrier] could easily be put in a new "In general" subsection, as I see in some other places.  That could also be done with the hanging paragraph in [thread.coord], but I would almost prefer to remove that text rather than make it a subclause.
