### ISSUE TITLE
[using.headers]/1 Not declaration, but directive?

### ISSUE THREAD

**Issue by onihusube** [cplusplus/draft#3194]
In [[using.headers] paragraph 1](http://eel.is/c++draft/using.headers#1)
>The entities in the C++ standard library are defined in headers, whose contents are made available to a translation unit when it contains the appropriate #include preprocessing directive ([cpp.include]) or the appropriate import declaration ([module.import]).

Isn't import declaration here import directive?

**Comment by jensmaurer** [comment]
Well, not really. The "import directive" is transformed into a _module-import-declaration_ [module.import], so that part is correct. Also, the term "entities" does not include macros, so this particular sentence, on the face of it, is not preprocessor-related.

(The sentence is broken, though, because it says "entities are defined in headers", which is probably not what we want to say: They should be declared in headers, and we don't care where they're actually defined.)
