### ISSUE TITLE
true and false should be in \tcode{} when refering to bool value

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#321]
In e-mail with Richard:
Dawn: In "or \tcode{alloca-tor_traits<allocator_type>::propagate_on_container_swap::value}
         is true within the implementation of the corresponding container operation."
    true should be in \tcode{} - ok to fix?  Should make global fix in single commit for similar uses?

Richard: Yes, in all cases where it's referring to the 'bool' value 'true' or 'false' we should \tcode it (but not in cases like 5.9/5, where it's referring to the mathematical notion of truth nor in [temp.expl.spec]p5's "The same is true when [...]").

**Comment by tkoeppe** [comment]
@burblebee, @zygoloid: Does https://github.com/cplusplus/draft/pull/977 address this problem? Does it fix it?

**Comment by jlaire** [comment]
In #977 I manually went through every match in `git grep true` and `git grep false`, but it's possible I missed some.

One of the less obvious cases I ran into is an integer value which is referred to as true (#978).

**Comment by tkoeppe** [comment]
@jensmaurer: Care to check whether this issue is now resolved? :-)

**Comment by jensmaurer** [comment]
$ grep -w false *.tex | grep -v tcode | grep -v "//" | grep -v static
still finds a few places that seem to be prose text and have "false" without \tcode in them.

**Comment by jlaire** [comment]
After removing codeblocks, the results of that grep have these three:

- Lines 1012-1013 in `atomics.tex`. I don't know if these should be have \tcode or not. Changing "the comparison is false" to "the result of the comparison is false" might be better in any case.
- Line 4712 in `locales.tex` should be changed to say "0" or "zero" instead of "false".
- Line 391 in `preprocessor.tex` (line 391), I don't know about this one.

I could create another PR, but if it's just a couple of changes it's probably easier for whoever can make the decisions to do it.

**Comment by jensmaurer** [comment]
The remaining ones are borderline and best left alone in this general issue.
