### ISSUE TITLE
[class.cdtor] Final overrider used incorrectly

### ISSUE THREAD

**Issue by 18** [cplusplus/draft#3218]
[[class.cdtor] p4](http://eel.is/c++draft/class.cdtor#4) says:
> [...] the object (call it x) under construction or destruction, the function called is the final overrider in the constructor's or destructor's class and not one overriding it in a more-derived class.

Final overrider is used as if it refers to a set of functions, which it does not, but rather a singular function. It would be better to say:
>  the function called is what would be the final overrider of the constructor's or destructor's class if it were the most-derived class.

**Comment by jensmaurer** [comment]
Editorial teleconference: The wording seems correct as written; whether a function is final overrider depends on which class it is considered a member of.

**Comment by sdkrystian** [comment]
I would argue differently. Consider the following:
```cpp
struct A
{
  virtual void f();
};

struct B : A
{
  void f(); // overrides A::f, is the final overrider
               // in a most derived object of type B
               // but not in a most derived object of type C
};

struct C : B
{
  void f(); // overrides A::f and B::f
               // is the final overrider 
               // in a most derived object of type C
};
```

So, when an base class subobject of type `B` belonging to an object of type `C` is under construction, `B::f()` simply isn't a final overrider because `C` declares a function that overrides `f`. For any given class type, there is only one final overrider for each virtual function.
