### ISSUE TITLE
literal isn't \grammarterm'd

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#322]
This issue was originally raised in the core reflector as "[c++std-core-25257] The definition of Literal is missing" on 12 May 2014 03:18, Saeed Amrollahi Boyouki.  An e-mail thread ensued, and it was decided that some of this could be resolved by fixing references to literal, when used as a grammar term, editorially, and to open a core issue for what remains.  Since there are 537 uses of literal in the spec, this is going to take a while...  See branch "literal-fixes" for this ongoing effort.

**Comment by jensmaurer** [comment]
I've had a look. It seems most mentions of "literal" in [lex] actually mentions a specific (and defined) kind of literal, e.g. "character literal" or "integer literal". There are a few cases where "literal" is used instead of the full phrase as a means of abbreviation. I'm preparing a patch that expands these.

[expr.prim.literal] does use \grammarterm {literal}, which is good.
