### ISSUE TITLE
[basic.def.odr] Why is "external linkage" only mentioned for inline functions & variables?

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#3237]
[\[basic.def.odr\]/12](http://eel.is/c++draft/basic.def.odr#12):

> There can be more than one definition of a
>
> - class type ([class]),
> - enumeration type ([dcl.enum]),
> - inline function or variable ([dcl.inline]) with external linkage,
> - [...]
>
> in a program provided that each definition appears in a different translation unit, [...].

Why is "external linkage" only mentioned in the third bullet? Why isn't it required for classes and enums?

AFAIK entities with internal linkage/no linkage cannot appear in multiple translation units, so they can't have more than one definition. (There can be definitions with the same spelling, but they nonetheless define different entities.) This applies to all entities: there's no reason to special-case inline functions & variables.

**Comment by jensmaurer** [comment]
Plus I think you can't have duplicate definitions with module linkage, either.

Since non-external linkage for classes and enums with more than one definition is made impossible by other rules (in particular, two definitions of internal-linkage classes wouldn't have the same name to start with; see also 6.5 [basic.link] p11), the phrasing here at most might give the wrong impression that there is permission for multiple definitions of non-external linkage types.

**Comment by jensmaurer** [comment]
Editorial teleconference: This needs to go to CWG.

**Comment by cpplearner** [comment]
Fixed by [CWG 2433](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1968r0.html#2433) (commit 2140e554b4c2b97e5d69845c5fbe1eb149600e03).
