### ISSUE TITLE
[std] There shall be no .1 subclause without a .2 sibling

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3525]
> A subclause shall not be created unless there is at least one further subclause at the same level. For example, text in Clause 10 shall not be designated subclause “10.1” unless there is also a subclause “10.2”.
> - https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor302

Affected subclauses, partially related to #574. Note that these are the parent subclauses of .1 subclauses without a .2 sibling:
- [x] [intro.compliance]
- [x] [dcl.spec.auto]
- [x] [class.mfct.non-static]
- [x] [class.union]
- [x] [allocator.requirements]
- [x] [cstdint]
- [x] [errno]
- [x] [c.locales]
- [x] [associative.reqmts]
- [x] [unord.req]
- [x] [unreachable.sentinels]
- [x] [view.interface]
- [x] [range.all]
- [x] [cfenv]
- [x] [conversions]
- [x] [fs.req]
- [x] [fs.class.filesystem.error]
- [x] [stopcallback]
- [x] [thread.sharedmutex.requirements]
- [x] [thread.sharedtimedmutex.requirements]
- [x] [depr.iterator.primitives]

**Comment by jwakely** [comment]
[class.union] looks ok

**Comment by jensmaurer** [comment]
@jwakely, how so? There is [class.union.anon] nested inside.

**Comment by jwakely** [comment]
Oh I misread the directive as only talking about a subclause with a single .1 paragraph. But if course ISO doesn't even number paragraphs, it's taking about subclause numbers. Sorry.

**Comment by jwakely** [comment]
N.B. the problem here is really that we have hanging paragraphs. If the content of [class.union] was in [class.union.xxx] then that would be a sibling of [class.union.anon], and we wouldn't be breaking this rule.

In the ISO world, where hanging paragraphs don't exist, a .1 subclause with no .2 sibling would mean the parent has no text of it's own and has an "only child". That's obviously pointless and the content of the only child could be moved up into the empty parent.

With hanging paragraphs the parent is not actually empty, and an only child can make sense.

**Comment by jensmaurer** [comment]
Editorial meeting: This is duplicative of the hanging paragraphs issue #1730.

**Comment by opensdh** [comment]
cplusplus/papers#533 plans to remove [class.this], making [class.mfct.non-static]'s paragraphs non-hanging.

**Comment by zygoloid** [comment]
I'm using this Perl script to find these:
```
$d = 0;                                                        
@secs = {}; @seclabels = {};
while (<>) {
  if ($_ =~ /\\rSec(\d)/) {
    if ($1 < $d && $secs[$d] == 1) { print "isolated subclause $seclabels[$d] in $seclabels[$d-1]\n"; }
    $d = $1;                       
    $sec = $_;
    chomp $sec;
    $secs[$d] += 1;
    $seclabels[$d] = $sec;
    $secs[$d + 1] = 0;
  }
}
```
