### ISSUE TITLE
[2020-02 LWG Poll 16] P1976R2 Fixed-size span construction from dynamic range

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3718]
resolves PL250

**Comment by jwakely** [comment]
Upon implementing this change I discovered it makes some other parts of the `span` spec ill-formed, due to `return { ... };` statements that use a constructor which is now explicit.

Since the spec is now contradictory, but the intention is clear, I think we should editorially add explicit types to [span.sub] p3 and p6, and [span.objectrep] p1 and p3.

If nobody objects to doing that, I'll take this issue and include those fixes.
