### ISSUE TITLE
Replace non-code "C++" with "\Cpp{}"

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3794]
I guess that `\Cpp{}` was introduced to avoid the hideous looking "++" with the PDF's font. There are plain "C++" that would look better if they were replaced with "\Cpp{}". `check.sh` should be enhanced to detect these. This may be obvious to pro LaTeX users, but pay attention to the index entries containing "C++". Some come from macro definitions like `\defnx{\Cpp{} standard library}{library!C++ standard}`, which should also replace the plain "C++" with "\Cpp{}" so that the index looks nice too.

**Comment by jensmaurer** [comment]
Extended the automatic checks is hard, because some mentions of C++ are actually intentional, e.g. in `extern "C++"`. Also, for index entries, there are two levels: one is the (sorting of) the index entry itself, and one is the presentation in the index. Only the latter can be replaced with the beautified macro.

**Comment by johelegp** [comment]
Very well. If it has to be done manually, I can submit a patch.

**Comment by johelegp** [comment]
Very well. If it has to be done manually, I can submit a patch.
