### ISSUE TITLE
library index not exactly in alphabetical order

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#398]
```
emplace, deque
push_front, deque
push_back, deque
```

are randomly collated between

```
input_iterator_tag
```

and

```
insert_after, forward_list
```

**Comment by AlisdairM** [comment]
This seems to be a deliberate decision in creating those index entries as related to 'insert' - I stumbled over this when cleaning up other mis-sortings due to use of '\tcode' in:
    https://github.com/cplusplus/draft/pull/741

This happens to be the one mis-filing I chose not to fix, as the use of 'insert@' in the index entry appears intentional - although I don't think that idiom is repeated anywhere else, and I would be happy to fix this too.

**Comment by jensmaurer** [comment]
Alisdair, I suggest that you submit a pull request to fix this.

**Comment by jensmaurer** [comment]
This particular issue is fixed.
