### ISSUE TITLE
[concepts.equality] Spurious "this document" wording

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/draft#3980]
In [concepts.equality] there are several normative phrases referring to "this document" such as in p3, p4, and p5. This phrase is used to define the locality of the term equality preservation which again has impact on how _requires-expression_'s are supposed to be interpreted. In theory "this document" can be interpreted in the widest possible form and could cover the complete International Standard (including core language). After a talk with Casey about the reason for this wording, he explained to me that this is a spurious left-over from the original Ranges-TS and is intended to cover the complete Standard Library specification. This issue is a modest attempt trying to ask whether "this document" in this [concepts.equality] subclause can be editorially changed to "throughout the library", or whether such a request would be non-editorially and would instead require an LWG issue.

**Comment by jensmaurer** [comment]
[concepts.equality] p4 "Expressions declared in a _requires-expression_ in this document are required to be equality-preserving, " seems to be the only case of the three mentioned ones where I can't squint the right way, and where a change is obviously normative.

But it's definitely strange to have such a requirement in a standard library section if it's supposed to apply to all core-language _requires-expression_ s. @zygoloid , can we fix that under the "pellucidly obvious" doctrine? Is it important enough to backport to the C++20 DIS branch?

**Comment by CaseyCarter** [comment]
Para 3 "Expressions required by this document to be equality-preserving are further required to be stable..." is correct as stated. I can't imagine _why_ we would require an expression in the Core clauses to be equality-preserving, but if we did this should apply. Para 4 "Expressions declared in a requires-expression in this document are required to be equality-preserving..." and 5 "This document uses a notational convention to specify which expressions declared in a requires-expression modify which inputs..."are only intended to cover the library clauses. I don't think it's the end of the world if someone is confused into the belief that an expression in a *requires-expression* in an example in the Core section of the IS is required to be equality-preserving, so I'd say there's no need to port such a change to the C++20 DIS.

**Comment by zygoloid** [comment]
I think I can squint at the existing wording the right way: the core language wording itself doesn't declare [sic] any expressions in *requires-expression*s (at least, outside of examples), it only describes how *requires-expression*s could constrain expressions within a user program. However, the library wording does specify expressions within *requires-expression*s, and this rule therefore applies to those. Core language examples are non-normative, so changing whether they're equality-preserving is immaterial.

So I'm OK with fixing this editorially to say that it applies only within the library clauses. I think the intent and meaning is sufficiently clear. And because I think the intent and meaning is sufficiently clear (and that the wording is technically correct already) I'm inclined to not make this change for C++20 post-DIS.
