### ISSUE TITLE
[class] Incorrect cross-references

### ISSUE THREAD

**Issue by kalaider** [cplusplus/draft#4004]
Some examples:

1. From [class.derived]. [basic.stc] is about storage duration, not layout. [expr.eq] is completely unrelated.
https://github.com/cplusplus/draft/blob/fc974c321e130e15e3be4eb12e213be00929d43a/source/classes.tex#L3588-L3597
2. From [class.access.spec]. [expr.rel] does not describe allocation order at all (and probably never did).
https://github.com/cplusplus/draft/blob/fc974c321e130e15e3be4eb12e213be00929d43a/source/classes.tex#L4714-L4717

The list is incomplete. Most broken references (if not all) point to either [basic] or [expr]. Other clauses seem more accurate.

**Comment by jensmaurer** [comment]
Regarding [class.derived], [expr.eq] p3.3 actually requires that comparisons of pointers to different complete objects yield the result "unequal", so this is in fact relevant. However, [intro.object] is probably a better reference. I agree the reference to [basic.stc] is bogus.

Regarding [class.access.spec], [expr.rel] p4.2 indeed discusses order of allocation, because pointer comparisons (but nothing else) induce constraints on the allocation order.

**Comment by kalaider** [comment]
Thanks for commenting on this.

Careful reading of [expr.eq] proved I jumped to somewhat wrong conclusions. However, it is still better to add some informal note regarding this directly under [expr.eq] subclause. [intro.object] addresses the issue directly, so, probably, the best solution is just to use it in place of [expr.eq].

In the passage from [class.access.spec]  _order of allocation_ is a bit confusing. [class.mem]/19 is about the same but its wording is much clearer. I missed that in essence subsequent allocations give higher addresses; without that the passage is pointless.

Also, I'll edit the title of the issue to be less radical.

**Comment by jensmaurer** [comment]
[class.mem] p19 is a note; everything there should be expressed normatively elsewhere.
