### ISSUE TITLE
[expr.unary.op]/8

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#4131]
[[expr.unary.op]/8](http://eel.is/c++draft/expr.unary#op-8):

> The operand of the unary `-` operator shall have arithmetic or unscoped enumeration type and the result is the **negation** of its operand. ...

The **negation** is obviously wrong.

**Comment by jensmaurer** [comment]
What other word would you suggest to use?

**Comment by jabelloc** [comment]
I would suggest the replacement of the word "negation" by "negative value".

**Comment by Eelis** [comment]
"negative value" could be a bit weird since the value might not actually be negative. "opposite" or "additive inverse" are options which don't have this problem.

**Comment by tkoeppe** [comment]
Just "negative" seems like an improvement: "the result is the negative of its operand". That's pretty standard terminology. (Indeed a negative need not be negative.)

**Comment by zygoloid** [comment]
> The **negation** is obviously wrong.

I don't think it's wrong; see [this question on English language stackexchange](https://english.stackexchange.com/questions/334194/whats-the-word-for-converting-a-positive-number-to-negative-one-and-negative-to). The unary operator `-` negates its operand, so the result is the negation of its operand. But I will happily accept that this usage of "negation" may not be familiar to all of our target audience; I'm happy to use a different word.

I don't think "negative" is an improvement. However, I think "additive inverse" would be an improvement, especially because it more directly means the right thing for unsigned types.

**Comment by tkoeppe** [comment]
@zygoloid: why is "negative" bad but "additive inverse" is acceptable? Isn't the former simply a name for the latter?

**Comment by jabelloc** [comment]
I took my old copy of Walter Rudin's book "Principles of Mathematical Analysis" (second edition), perhaps one of the most renowned academic texts on the subject, for graduate courses. After a brief rereading of his first chapter "The Real and Complex Number System", I did not identify a single time that the author referred to the `-` sign as a **negation**. But there are references in this chapter to the terms **negative cut** or **positive cut**, which are mathematical abstractions used by Dedekind to define the set of rational numbers. I haven't checked this thing out for the whole book, but I don't remember ever seeing the word **negation** associated with the `-` sign, in any math book that I had a chance to read or study in my life.

**Comment by zygoloid** [comment]
ISO/IEC 2382:2015 defines:

> **negation**  
> NOT operation  
> Boolean complementation  
> inversion
>
> monadic Boolean operation whose result has the Boolean value opposite to that of the operand

That's not what we mean here, so we should certainly change this wording (regardless of whether our readership is or is not familiar with this usage of this word). It also defines:

> **negate**
>
> perform the operation of negation

... so we can't use that either, except to describe the operation of `!` or `~`.

> @zygoloid: why is "negative" bad but "additive inverse" is acceptable? Isn't the former simply a name for the latter?

"Negative" also refers to the set of numbers less than zero. Indeed, while ISO/IEC 2382:2015 does not define "negative", it uses it exclusively to refer to numbers less than zero. Also, in my experience it's not common to refer to the additive inverse of an element in an arbitrary ring (such as the ring modeled by an unsigned type) as the negative of that element. I think, for the most part, "additive inverse" uniquely identifies the operation we're looking for here.

Hm. But "additive inverse" doesn't work for floating-point types, because +inf doesn't have an additive inverse, but unary minus is typically still well-defined when applied to it. It's also wrong in the presence of signed zeroes, wherein `0` does not have an additive inverse: there is nothing that can be added to `-0.0 + 0.0` (== `0.0`) to get `-0.0`.

So:

- "negation" and "negate" are out (ISO/IEC 2382 defines them as something else)
- "negative" is questionable (not really appropriate for unsigned types, and risks confusion with property of being negative)
- "additive inverse" is out (wrong for floating-point infinity and zero)
- "with the sign {flipped/reversed/inverted}" / "with the opposite sign" is somewhat unnatural for unsigned types and probably overconstraining for floating point
- "the result of subtracting the operand from zero" almost works, but is also wrong for negative zeroes (`0.0 - 0.0` is positive zero)
- "the result of subtracting the operand from negative zero" works, but is very strange
- "the result of multiplying the operand by -1" seems to work in all cases, but it's not ideal for unsigned types

I'm not entirely happy with any of these options.

**Comment by zygoloid** [comment]
C uses "negative of" for this purpose. I think that's enough motivation to prefer that word, even though it's not ideal for unsigned types.
