### ISSUE TITLE
consider moving [declval]p4 inside the itemdescr

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4266]
[declval]p4 appears to be an example for the `declval` function, so should be indented with the rest of the function's detailed description.

**Comment by zygoloid** [comment]
Also, "participates in overloading" should be "participates in overload resolution".

**Comment by jwakely** [comment]
Arguably the example goes with [declval] p1 by showing an example of using `declval` to simplify the definition of expressions which occur as unevaluated operands. Indenting it as part of the itemdescr seems equally correct though.

As for the second point, that is obviously an improvement. But ... is it actually correct for the library to talk about function templates not participating in overload resolution because of deduction failures? They still participate, in that they are in the initial candidate set, deduction fails, and they are removed from the set. Isn't that failed deduction part of overload resolution? Would it be more precise to replace "only participates in overload resolution if" with "is removed from the candidate set during overload resolution unless"?

Not in scope for C++20 obviously. But if we wanted to change it, there are only a handful of places to change in the library now. The introduction of the _Constraints:_ element in [structure.specification] replaced nearly 300 occurrences  of "shall not participate in overload resolution unless".

**Comment by jensmaurer** [comment]
Let's fix the narrow issue with declval here. @jwakely, if you feel we should revisit the phrasing "participates in overload resolution", please create separate, dedicated issue marked "decision-required".
