### ISSUE TITLE
[unord.hash] Redundant wording LWG 3512

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#4437]
[[unord.hash]p5.4](http://eel.is/c++draft/unord.hash#5.4) ends with "shall not throw an exception unless `hash<Key>` is a program-defined specialization that depends on at least one program-defined type."

"that depends on at least one program-defined type" is redundant given [[namespace.std]p2](http://eel.is/c++draft/namespace.std#2): "Unless explicitly prohibited, a program may add a template specialization for any standard library class template to namespace std provided that (a) the added declaration depends on at least one program-defined type ..."

**Comment by jwakely** [comment]
I agree those words are redundant, but is that wording even true? If the hash function is `hash<optional<T>>` then it's not a program-defined specialization, but it can throw if `hash<T>` can throw.

Rather than fixing the redundancy as an editorial issue, we need to fix the falsehood as an LWG issue.

**Comment by johelegp** [comment]
You're right. Fortunately, the redundant part comes after the falsehood part.

**Comment by Dani-Hub** [comment]
A corresponding LWG issue exists now: [LWG 3512](https://cplusplus.github.io/LWG/issue3512)
