### ISSUE TITLE
20.10.6 [meta.rel] says "return-statement"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#445]
Should probably be "return statement"

**Comment by zygoloid** [comment]
I think you mean this, from p4:

> Access checking is performed as if in a context unrelated to `To` and `From`. Only the validity
of the immediate context of the expression of the *return-statement* (including conversions to the return type) is considered. [Note: The evaluation of the conversion can result in side effects such as the instantiation of class template specializations and function template specializations, the generation of implicitly-defined functions, and so on. Such side effects are not in the “immediate context” and can result in the program being ill-formed.]

This is wrong in quite a few ways ("evaluation" and "side effect" are defined to mean something completely different from what this note is talking about, there is no such thing as a *return-statement*, the "as if" is noise since it's already implied for all rules in the standard, ...). How about this:

> Access checking is performed in a context unrelated to `To` and `From`. Only the validity of the immediate context of the *expression* in the `return` statement (including the initialization of the returned object or reference) is considered. [Note: The initialization can result in effects such as the instantiation of class template specializations and function template specializations, the generation of implicitly-defined
functions, and so on. Such effects are not in the “immediate context” and can result in the program
being ill-formed.]

The bogus "side effects" / "evaluation" wording also appears in [temp.deduct]/8 and Table 49 in [meta.unary.prop]; we should either fix it everywhere, or preferably just refer back to [temp.deduct] for the implications of "immediate context". It'd be good to make [temp.deduct] actually define this rather than hand-wave...

**Comment by jwakely** [comment]
I actually meant the text earlier in that paragraph, between the two code blocks:

> if and only if the return expression in the following code would be well-formed,

but I agree the part you quote also has problems (and like your suggested changes).

**Comment by jwakely** [comment]
(Oops, just deleted my comment instead of editing it)

I actually meant this text earlier in the paragraph, between the two code blocks:

> only if the return expression in the following code would be well-formed,

But I agree with the other problems you spotted, and your suggested fixes.

**Comment by jensmaurer** [comment]
The "immediate context" phrasing, including the note, has spawned throughout [meta], it seems.

**Comment by jensmaurer** [comment]
The "immediate context" concerns are covered by [LWG 2290](http://cplusplus.github.io/LWG/lwg-active.html#2290) "Top-level "SFINAE"-based constraints should get a separate definition in Clause 17".

**Comment by jensmaurer** [comment]
#1252 fixes [temp.deduct] to avoid "side effect" and "evaluation".
