### ISSUE TITLE
Synopsis in [support.exception] gives no clue that uncaught_exception() is in [depr.uncaught]

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#485]
There should be a cross-reference from the synopsis to "D.9, uncaught_exception (deprecated)"

Also [ostream::sentry] still uses the deprecated version, it should be updated to use `uncaught_exceptions()`

**Comment by jwakely** [comment]
Fixed at eb009db

**Comment by cpplearner** [comment]
I think [ostream::sentry] could use `uncaught_exceptions()` more cleverly, i.e. store `uncaught_exceptions()` on construction, and during the destruction, compare `uncaught_exceptions()` with the stored value, then decide whether it should call `os.rdbuf()->pubsync()` based on the result of the comparison, instead of on `!uncaught_exceptions()`.

**Comment by jwakely** [comment]
That would not be an editorial change, so doesn't belong in this issues list.
