### ISSUE TITLE
[basic.type.qualifier] The ordering defined on cv-qualifiers is not a partial ordering

### ISSUE THREAD

**Issue by Little-He-Guan** [cplusplus/draft#4908]
The fourth paragraph in [basic.type.qualifier] says that

> There is a partial ordering on cv-qualifiers, so that a type can be
said to be \defn{more cv-qualified} than another.
\tref{basic.type.qualifier.rel} shows the relations that
constitute this ordering.

However, the ordering defined in table `basic.type.qualifier.rel` is not a partial ordering, since that there exists two cv-qualifiers (namely, _const_ and _volatile_) for which the ordering is not defined.

I guess it intends to mean that the ordering is partially defined on the cv-qualifiers. But the term partially ordering is not defined this way. The definition of a partially ordered set requires that the ordering is defined on every two elements of the set (i.e. the ordering relation is either true or false between any two elements).

I don't know if this issue seems to be overcorrect... I noticed the phrase "partial ordering" because I recently learned concepts about ordered sets. I apologize if the issue is really overcorrect.

**Comment by tkoeppe** [comment]
I don't think the problem as you stated is correct.

> The definition of a partially ordered set requires that the ordering is defined on every two elements of the set (i.e. the ordering relation is either true or false between any two elements).

This is not true. A partial order need not be defined on every pair of elements. The partial order axioms only apply to those orderings that _are_ defined. For example, "if a < b and b < c, then a < c" -- but it is not required that a and b are comparable to begin with. See also https://en.wikipedia.org/wiki/Partially_ordered_set. (Consider the canonical example of the "subset" relation on the elements of the power set of any given set.)

**Comment by Little-He-Guan** [comment]
Hello tkoeppe,
The requirement for the ordering to be either true or false comes from that it is a relation (the Wikipedia page also mentions it). 

A relation _R_ over a set _S_  may be defined as a subset of _S_ × _S_, and therefore must be either true or false for any two elements in _S_, because the statement (x,y) ∈ _R_ is either true or false.

**Comment by tkoeppe** [comment]
I'm not sure if there is a contradiction here. As you say, _R_ is a *subset* (and usually a strict one!) of _S_ × _S_, so some elements may be related, but others may not. X is more cv-qualfied than Y if (X, Y) is a relation, otherwise it is not so. The table you quote describes precisely that set _R_ of relations, everything not in the table is not a relation.

**Comment by Little-He-Guan** [comment]
Hello tkoeppe, 
Suppose we have < as a relation over _S_, then

1. (x,  y) ∈ _S × S_ means that x < y is true, and
2. (x,  y) ∉ _S × S_ means that x < y is false

Nevertheless, you remind me of that we may treat all relations not defined on the table as if they are false (e.g. const < volatile is not defined on the table, so const < volatile is false). And this is a valid interpretation.

Anyway, thank you for your review. :)

**Comment by tkoeppe** [comment]
Yes, and again I don't think there's any problem or contradiction here. For example, you may say "const < volatile is false", if you like, that's accurate, and consistent with what we say in the standard (where "<" means "more cv-qualified"), or in other words, "it is not the case that const is more cv-qualified than volatile".

Your original complaint that an ordering is not defined for all pairs is merely a restatement of the observation that there exists x, y such that (x, y) ∉ _R_. Or in yet other words, in order to state a partial order, it suffices to state _R_, and it is not necessary to also state the complement of _R_.
