### ISSUE TITLE
[tuple.apply] Redundant/inconsistent std:: qualification for std::get

### ISSUE THREAD

**Issue by dangelog** [cplusplus/draft#4948]
The definition of `std::apply` uses `std::get`, although spelling `std::` shouldn't be necessary (due to the [contents]). In the very same section, `std::make_from_tuple` calls `get` without qualification. It would be nice to unify the two one way or another.

**Comment by jensmaurer** [comment]
The problem is that neither apply-impl nor make-from-tuple-impl are shown to be in namespace `std`, so that unqualified lookup doesn't actually find `std::get`.

@jwakely, what's your preference:
- put apply-impl and make-from-tuple-impl inside namespace std and get rid of `std::` in `std::get` or
-  leave the namespaces as-is and qualify `get` and `index_sequence` in make-from-tuple-impl and apply-impl.

**Comment by dangelog** [comment]
Hi,
That's a good point. I guess qualifying is a good idea, given also the presence of `forward` in there?

**Comment by jensmaurer** [comment]
No, `std::forward` and `std::move` are special (by convention in the standard; nothing special about them per se).

**Comment by CaseyCarter** [comment]
I'd prefer wrapping our exposition-only functions with `namespace std {}` to avoid confusion. I could live with fully-qualifying all names in such functions as if they were in the global namespace. I would rather _not_ have some names qualified (`std::get`) and others not (`size_t`, `index_sequence`) without good reason. ("We always qualify `move` and `forward`" isn't a good reason, but that's really a separate issue.)

**Comment by jwakely** [comment]
I agree with Casey.
