### ISSUE TITLE
 P0288R9 move_only_function editorial fixes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#4960]
- [x] [func.wrap.mov.con] Args -> ArgTypes
- [ ] Create LWG issue to make move assignment operator noexcept
- [x]  "f is lvalue of type F" -> "and F is the type of that target object"
- [x] change phrasing "targets an object" to "has a target object"
- [x] change phrasing "targets an object" to "has a target object" for std::function [func.wrap.func.con], too

See http://lists.isocpp.org/lib/2021/10/20588.php

**Comment by jensmaurer** [comment]
@jwakely , do we have those LWG issues?

**Comment by jwakely** [comment]
The wording in the paper reflects the design that was approved. If you think the design was wrong, please file an LWG issue.

I find it very hard to care about code that does `f = std::in_place_type<int(*)()>` because that seems very unlikely to happen by mistake, and if you want to do something so silly, then go ahead.

This also compiles fine, despite being useless and silly:
```
std::move_only_function<int()> f(std::in_place_type<int(*)()>);
```

If you want to store a null pointer you can do so with `nullptr`, or with silly nonsense like this. :shrug:
