### ISSUE TITLE
[basic.ios.members] p16 has numbered list that should use bullets

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#505]
The definition of `copyfmt` in p16 has a numbered list with a bulletted list nested inside it, so only the inner list gets the new (16.1), 16.2) bullet numbering, which looks very odd.

**Comment by AlisdairM** [comment]
It may look odd, but I think the format is intentional.  The outer list is an ordered sequence of events, where the order matters.  The inner bullet list states 3 properties of the copy behavior, but there is no relative sequencing between them, so the associated para-number for the bullet is not semantically useful, but provides a way to identify those sentences in the standard.

**Comment by jensmaurer** [comment]
Maybe we want to give numbered lists the same "number-in-margin" treatment as bulleted lists?

**Comment by Eelis** [comment]
For reference, here's a screenshot: ![item](http://eel.is/it.png)
Another solution could be to keep the styling as-is, but change the numbers for the nested items to (16.2.1), (16.2.2), and (16.2.3), to reflect that they are nested in item 2 of para 16.

**Comment by zygoloid** [comment]
Decision: add "then," to the start of the second, third, and fourth item, and convert to bullets.

[cmplx.over]: convert to bullets
[streambuf.virt.put]: p5 should be converted to bullets, first bullet is missing a period.

In general: where the numbers are not semantically important (eg, not for phases of translation), convert to bullets. Use words, not numbering, to indicate sequencing.

**Comment by jwakely** [comment]
Fixed at ee8aa525e65ada1f1949ebc9eb006af8b29f7e85
