### ISSUE TITLE
Index entries for range adaptors in namespace views

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5831]
For other entities in a nested namespace, we just index its name, not its scope. For example, the index contains `steady_clock`, not `chrono|steady_clock`, and `duration` not `chrono|duration`, and `adjacent_view` not `ranges|adjacent_view`.

But then for the range adaptors we have `views|adjacent`, `views|drop` etc.

![image](https://user-images.githubusercontent.com/1254480/190143074-7e7af924-8d32-4c0f-ac4b-34ccffdda574.png)

Was this a deliberate choice?

**Comment by jensmaurer** [comment]
Yes, the choice was deliberate ("drop" is too generic a name), but maybe it's not sufficiently consistent.

**Comment by jensmaurer** [comment]
@tkoeppe , what do you think?

**Comment by tkoeppe** [comment]
First and foremost, the index needs to be _useful_ more than it needs to be _consistent_. If generic names benefit from context, I can see that being useful. It's not that surprising that durations or clocks have to do with chrono, but for the range adaptors there is otherwise litlte context -- what kind of "chunk" are we talking about?

So the status quo seems fine.

If you really wanted to, you could add the namespace to the "chrono" and "ranges" names, but I'm not sure that would improve the usability of the index. If in doubt, I'd leave it as is.

**Comment by jwakely** [comment]
OK, works for me. Feel free to close this.

**Comment by tkoeppe** [comment]
Thanks!
