### ISSUE TITLE
[temp] Overall definition of term "template"

### ISSUE THREAD

**Issue by FrankHB** [cplusplus/draft#593]
Moved from #425:

[temp]

> 1 A _template_ defines a family of classes or functions or an alias for a family of types.

Variable templates should be listed alone.

Should the static data members also be here?

**Comment by jensmaurer** [comment]
On the face of it, this is a fairly trivial issue: When we added variable templates, we didn't augment the definition of "template". I don't think we need to make this bigger than necessary, given that we don't refer to a plain "template" often (because it's not a super-useful term in its generality).

Note that we nowadays have the term "templated entity" that can be used when we wan to talk about "something that is dependent on a template parameter".

Thus, I'll re-offer the change from #425 (with the Oxford comma) as the appropriate fix here.
