### ISSUE TITLE
[re.results.const] Sentence can be a note

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#6138]
The approved to-be-added sentence https://github.com/cplusplus/draft/pull/6124/commits/d15847c097fd5c3b0c6ed45ca977948f592bdba6#diff-4d5ed3db3c14cde067617b4a10d4377b149fba4e8a7108228a6fbe63fbf909dfR2256-R2258 can be a note. Should it be made into a note? The wiki and ISO Directives, Part 2 just mention that notes are not normative. So what's the C++ Standard's standard for choosing to note or not to note?

**Comment by jensmaurer** [comment]
In general, we try to avoid normative duplication. If we feel a non-obvious normative rule (or consequence of normative rules) needs to be highlighted, we add a note.

In this case, I think even the normative duplication (which, in this case, doesn't really re-state a rule, but just points to one, so is less in danger of becoming inconsistent) is good, because it makes sure we've very transparently covered all cases.

**Comment by JohelEGP** [comment]
Thank you for the explanation. I agree that this is good.
