### ISSUE TITLE
[2023-06 CWG Motion 4] P2361R6 Unevaluated strings

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6279]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2361r6.pdf

**Comment by tkoeppe** [comment]
Mail from @cor3ntin:

> in dcl.pre/p10, there is a minor conflict between P2361 and the current draft.
However, P2741R3 also on the ballot, assumes P2361 is going to get approved,
so i would recommend
>
> - Merging P2741R3 before P2361
> - When applying P2361, do not apply the changes in dcl.pre/p10 and dcl.pre/p1, as P2741R3 contains these changes already.

**Comment by tkoeppe** [comment]
Hm, merging motions out of order is a bit unusual. @jensmaurer Let me know if you need any advice on this, otherwise I'll leave you to figure something out (but do say in the commit message how this is being reconciled).

@cor3ntin Could you please point out the prior change that causes the merge conflict between your paper and the current draft?
