### ISSUE TITLE
[atomics.types.operations] p7 What if the supplied arguments does not denote any enumerator?

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#6511]
> void store(T desired, memory_order order = memory_order::seq_cst) volatile noexcept;
> void store(T desired, memory_order order = memory_order::seq_cst) noexcept;
>
> Preconditions: The order argument is neither memory_order​::​consume, memory_order​::​acquire, nor memory_order​::​acq_rel.

The LWG side asked me to open an editorial post about this issue, even though I have already tried to report an issue on CWG, and the CWG side(https://github.com/cplusplus/CWG/issues/398) has confirmed that this issue should be reported as an LWG issue. The original issue is:
````cpp
#include <atomic>
int main(){
   std::atomic<int> v{0};
   auto invented_ordering = static_cast<std::memory_order>(1024);
   v.store(1,invented_ordering);
}
````
[enum.dcl.enum] p8 says:
>  It is possible to define an enumeration that has values not defined by any of its enumerators. 

The `invented_ordering` does not violate the preconditions of the store, however, this is obviously problematic.

**Comment by Dani-Hub** [comment]
Before the project editors close this as non-editorially I would like to remind that the corresponding _Effects:_ are defined as follows: 
"[...] Memory is affected according to the value of order."
But the standard does not define the meaning of `std::memory_order(1024)`, so to me one can argue that it is possible to solve this editorially by re-expressing the _Preconditions:_ in a positive form listing only the valid values, since the user cannot rely on a concrete effect anyway.

**Comment by jensmaurer** [comment]
Patch welcome to express the preconditions as a positive list.

**Comment by Dani-Hub** [comment]
I will work on that

**Comment by Dani-Hub** [comment]
There exists now PULL request #6518.
