### ISSUE TITLE
[thread.threads] Namespace indentation 

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#66]
From an email to cxxeditor@:

I also suggest to indent all members of namespace this_thread in 30.3 Threads [thread.threads].

Currently optically you can't see that they are defined INSIDE namespace this_thread.

**Comment by lefticus** [comment]
## Investigation Update

I've investigated this issue and found the root causes:

### Problem Summary
There are **14 total instances** of unconverted cross-references across 5 files:
- **6 instances**: `@@REF:label@@` placeholders in footnotes (never converted to wikilinks)
- **8 instances**: `// REF:label` in code comments (**CORRECT - these are intentional**)

### Affected Files with Problems

**support.md:**
- Line 1997: `objectREF:basic.life` - missing space before REF, should be `[basic.life]`
- Line 4384: `@@REF:basic.start.main@@` - footnote placeholder never converted

**input.md:**
- Line 12598: `@@REF:stringbuf,filebuf@@` - footnote placeholder never converted
- Line 12615: `@@REF:istream.manip@@` - footnote placeholder never converted
- Line 12618: `@@REF:basefield.manip@@` - footnote placeholder never converted
- Line 12651: `@@REF:ostream.manip@@` - footnote placeholder never converted
- Line 12654: `@@REF:basefield.manip@@` - footnote placeholder never converted

### Root Cause

Looking at the codebase architecture:

1. **cpp-common.lua** lines 2452-2455 converts `\iref{}`, `\ref{}`, `\tref{}` to `@@REF:label@@` placeholders (when `ref_format == "placeholder"`)

2. **cpp-itemdecl.lua** lines 115-174 and **cpp-macros.lua** line 1021 convert `@@REF:label@@` to `[[label]]` wikilinks

3. **The bug:** This conversion only happens in **specific contexts**:
   - Inside `\itemdescr{}` blocks (cpp-itemdecl.lua)
   - Inside `\stage{}` descriptions (cpp-macros.lua)

4. **Footnotes are NOT processed** by either filter, so `@@REF:...@@` placeholders remain unconverted

### Fix Required

Need to add a **global post-processing step** to convert remaining `@@REF:label@@` placeholders to `[[label]]` wikilinks in ALL contexts, not just itemdescr and stage blocks.

This could be:
- A new filter that runs late in the pipeline
- An extension to an existing filter (like cpp-macros.lua)
- A Pandoc walker that processes all inline elements

Will work on a fix next.
