### ISSUE TITLE
[basic.pre] Eliminate the redundant block-declaration

### ISSUE THREAD

**Issue by ContingencyOfTautologicalContradictions** [cplusplus/draft#6628]
https://eel.is/c++draft/basic.pre#5.1 mentions the following:

> name-declaration, block-declaration, or member-declaration ([dcl.pre], [class.mem]),

That block-declaration is already given inside the name-declaration (at https://eel.is/c++draft/dcl.pre#nt:name-declaration), hence it is redundant and should be eliminated

**Comment by jensmaurer** [comment]
_block-declaration_ is used for _declaration-statement_. You can't use a _name-declaration_ there.
When we say _name-declaration_ (or similar), we usually mean the immediate appearance of that grammar non-terminal quoted from a grammar production.

In short, the current phrasing seems intentional and desirable.
