### ISSUE TITLE
Overlong line in [syserr.errcode.nonmembers]

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#676]
> 2 _Returns:_ `lhs.category() < rhs.category() || lhs.category() == rhs.category() && lhs.value()`
>  `< rhs.value()`

It doesn't want to break before `lhs.value()`, or even after `lhs`.

I can make it `lhs.val-` \\ `ue()` but ick.

**Comment by tkoeppe** [comment]
Use a code block rather than display it inline?

**Comment by burblebee** [comment]
I've seen code blocks used elsewhere to solve this problem.

BTW, there are a ton of "Overfull" warnings emitted now from Latex.  Can you go through and fix them all?  (Rather than opening up a separate github issue for each one).  We also get a ton of "Underfull" warnings - what causes those?  I'll open a github issue for the "Underfull" warnings.

**Comment by jensmaurer** [comment]
This is a special case of #693.

**Comment by jensmaurer** [comment]
The original issue seems to be using a codeblock these days.
