### ISSUE TITLE
"Equivalent to return foo();" vs. "Equivalent to foo()".

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#679]
Outside of [this commit](https://github.com/cplusplus/draft/commit/4d1ede227c6105ea420ea3c72649ab5ce977ff1d), it looks like most uses of the magic words "equivalent to" for a value-returning function is of the form

> _Effects:_ Equivalent to `return foo();`

or

> _Effects:_ Equivalent to `foo()`
> _Returns:_ `bar`.

That commit stripped a bunch of `return`s from "equivalent to"s of the first form, so that it's instead

> _Effects:_ Equivalent to `foo()`.

The inconsistency seems...odd.

**Comment by burblebee** [comment]
The returns which were removed in that commit were added back in 0586a06705d7ba332771f47cb98ab09ea36988a1 after some discussion with library folks and Richard.  As it turns out, you can either describe the return value via a 'return' there in the Effects:, or in a Returns: clause.    It seems to be up to the library authors as to which method they prefer to use.  That said, the inconsistency bothers me too - I found it to be confusing.

I don't know if you want to close this now, given that the inconsistency appears to be intended?  I did ask the library folks to go through the spec and make sure the returns/Returns are how they want them to be, as part of a related issue.

One thing I'd like to change is to add a : after the Equivalent to: when it is followed by a code block - I think that would help to at least know when we are introducing a code block, but no one has replied to me on that.

**Comment by tkoeppe** [comment]
I think there's a distinction: "_Effects_: Equivalent to `return foo();`" leaves it up to the implementation, whereas "_Returns_: `foo()`." prescribes a specific implementation.

**Comment by jensmaurer** [comment]
Note that "Equivalent to" has special meaning; see 17.4.1.4p4.

**Comment by jensmaurer** [comment]
I don't think there's anything to be done for this issue that wouldn't be covered by #1119.
