### ISSUE TITLE
[inplace.vector.syn] Missing default template argument for `erase`

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#7149]
The default template argument is present in [[inplace.vector.erasure]](https://eel.is/c++draft/inplace.vector.erasure), and it should also be in the synopsis.

Is an LWG issue needed to fix this as the inconsistency was originally in [P0843R14](https://wg21.link/p0843r14)?

**Comment by jwakely** [comment]
No, this is obviously editorial:
https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial
(the first broad category).

The template arg is present in the detailed description, and is present for all other `erase` overloads since #6911 so it's an obvious inconsistency that it's missing from the `<inplace_vector>` synopsis.
