### ISSUE TITLE
\pnums in effects/returns/etc. are confusing

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#821]
When a \pnum is used within an effects/returns/etc. clause, it's not possible to tell if the new paragraph is part of that clause, or is a new paragraph that happens to follow the clause.
For example, where do the effects end in the following? :
1. _Effects_: bla bla.
2. bla bla bla.  This paragraph is part of the effects.
3. Let X be bla.  This is a new paragraph introducing X for the paragraphs that follow.
4. _Returns_: X.

This makes it clear:
1. _Effects_: bla bla.<br/>
   bla bla bla.  This paragraph is part of the effects.
2. Let X be bla.  This is a new paragraph introducing X for the paragraphs that follow.
3. _Returns_: X.

It would be good to have a way to fix the issue above. If not by replacing \pnums with \pars, then how?

Note: This was originally part of issue #781, but we could not come up with a resolution for it, so it was separated out into its own issue so that the rest of #781 can be resolved and closed.  See the discussions in #781.

**Comment by jwakely** [comment]
I disagree that it's not possible to tell, because as far as I'm aware they're **always** part of that clause. (Unless you have examples where that isn't the case?)

**Comment by jwakely** [comment]
We have some paragraphs that come first, before any of the _Effects:_ or _Returns:_ elements, e.g. to introduce variables that are used in the elements that follow e.g. [tuple.creation] p2. But they're unambiguous, they're not part of the _Effects:_ or anything else, because they come before them.

But if all paragraphs that come after one of the named elements are part of the previous element, then that's also unambiguous, and I see no need to change anything.

**Comment by jensmaurer** [comment]
@burblebee: Do you have specific examples where @jwakely's assertion is false? Please state them for inspection.

**Comment by jensmaurer** [comment]
Closing for lack of specific examples that need work.
