### ISSUE TITLE
<string_view> is missing from the list of headers in  [iterator.range]/1:

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#963]
(from a request to open an LWG issue by Johel Ernesto Guerrero Peña <johelegp@gmail.com>; I'm opening this issue because I believe its' editorial):

[string.view.synop]/1 states:

The function templates defined in 20.2.2 and 24.7 are available when <string_view> is included.

But the list of headers in 24.7 or [iterator.range]/1 is missing <string_view>.

Proposed resolution:

This wording is relative to N4606.

Modify [iterator.range]/1:

In addition to being available via inclusion of the <iterator> header, the function templates in 24.7 are available when any of the following headers are included: <array>, <deque>, <forward_list>, <list>, <map>, <regex>, <set>, <string><ins>, <string_view></ins>, <unordered_map>, <unordered_set>, and <vector>.

**Comment by johelegp** [comment]
PR #962 fixes this.

I had submitted an earlier LWG issue, to which Daniel Krügler replied that it might be an editorial request, and pointed me to open an issue here (I had failed to find this place for submitting editorial fixes.)

I opted to do PRs for both issues instead, because I believe the wiki here suggests that these are editorial fixes as they fall in the "obvious inconsistencies" category.

**Comment by mclow** [comment]
I saw that Daniel suggested you submit an editorial request for a different problem (`iterator_traits<const T*>`), but didn't see your other P/R for the second one.  Thanks for doing this.
